language: ruby

sudo: false

rvm:
  - 2.3.1

env:
  global:
    - ES_VERSION=2.2.0
    - ES_BIN=elasticsearch/bin/elasticsearch

before_install:
  - "mkdir ${TRAVIS_BUILD_DIR}/elasticsearch"
  - "wget -O - https://download.elasticsearch.org/elasticsearch/release/org/elasticsearch/distribution/tar/elasticsearch/${ES_VERSION}/elasticsearch-${ES_VERSION}.tar.gz | tar xz --directory=${TRAVIS_BUILD_DIR}/elasticsearch --strip-components=1"
